name: shelf_enforces_ssl
description: Enforces that users can only make API requests over HTTPS (SSL).
version: 1.1.0
homepage: https://jxstxn.de
repository: https://github.com/jxstxn1/shelf_enforces_ssl

environment:
  sdk: '>=2.18.0 <3.0.0'

dependencies: 
  shelf: ^1.3.2


dev_dependencies:
  lint: ^1.0.0
  test: ^1.16.0
